// <auto-generated />
namespace Practical.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class My11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(My11));
        
        string IMigrationMetadata.Id
        {
            get { return "202011300958535_My11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
